services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard-home
    restart: unless-stopped
    ports:
      - 53:53/tcp # Ports have to be formatted this way
      - 53:53/udp
      - ${ADMIN_PORT}:80 # Admin Panel
      - ${SETUP_PORT}:3000 # Setup Port
    volumes:
      - /etc/timezone:/etc/timezone
      - ${WORK_DIR}:/opt/adguardhome/work
      - ${CONF_DIR}:/opt/adguardhome/conf